### ISSUE TITLE
Script overwriting stories with similar names

### ISSUE THREAD

**Issue by rabea98** [notcammy/PySnapStories#3] opened 2020-01-06 06:02 UTC
Hi Dirk,
It seems that the script overwrites any stories from a certain user that has the same name, for some reason the stories filenames aren't unique, like if you download a story and try to download another story a week later ( from the same user ), there's a high chance that they would have the same filenames and the script would overwrite the old files.
Also, lets say I'm scraping "sommerray" stories, the script would make a folder by the name "sommerray_NoTitle" , if you create folders inside that folder , the script would delete them also.
I'm not sure on how to reproduce this bug.

**Comment by rabea98** [comment] 2020-01-06 06:18
A horrible solution to this would be to write a script that copies all the stories downloaded to an archive folder, and if it finds a file with the same name then compare hash or size to decide to overwrite or to add something at the end of the filename.
The script would run each time when a download is invoked.

**Comment by dvingerh** [comment] 2020-01-06 09:58
Downloads will now include epoch timestamp of the Snapchat api response itself, which *should* be unique. I can't reproduce the folder deleting behavior as such I'll close this issue. Not sure how it would delete folders since there are no functions being called that would cause this to happen

**Closed as completed by dvingerh** 2020-01-06 09:58 UTC
Labels: bug

**Comment by rabea98** [comment] 2020-01-07 04:08
Thanks for the fix.
I will try to figure out how to reproduce the other bug.

**Comment by rabea98** [comment] 2020-01-11 01:25
Hi @notcammy 
I was able to reproduce the bug where the script deletes saved stories inside a user folder.
Keep this batch script running 24/7:
[f.zip](https://github.com/notcammy/PySnapStories/files/4048817/f.zip)

The bug occurs on one particular user, "brightonrose"  .
add the user on your phone and monitor the stories, you will see that after a couple of days the script deletes previous saved stories from "brightonrose"

**Comment by dvingerh** [comment] 2020-01-12 16:02
Theoretically it shouldn't overwrite anything since it checks if the file already exists in https://github.com/notcammy/PySnapStories/blob/master/pysnapstories.py#L471

Im probably missing something super obvious but yeah dont know how to fix at the moment
I'll run the script for that user and see whats up

**Comment by rabea98** [comment] 2020-01-14 04:07
Thank you for looking into the matter.
You should turn on push notification for that user, I encountered the issue again today, the main folder that user got deleted.

**Comment by dvingerh** [comment] 2020-01-14 13:41
Snapchat API is simply not reliable enough for me to write a good script for with the very little time i have, as such I've decided to abandon the project for indefinite amount of time

You can still manually grab them from these endspoints
https://search.snapchat.com/lookupStory?id=sommerray
https://storysharing.snapchat.com/v1/fetch/itsleah04?request_origin=ORIGIN_WEB_PLAYER

At the moment second endpoint works better i think, some user isn't returning anything for me atm on the first endpoint while it does on the second
for the second endpoint if video has overlay change embedded.mp4 to media.mp4 in the url

**Comment by rabea98** [comment] 2020-01-14 19:07
Sorry to hear that you are abandoning the project.
It looks like everyone is giving up on snapchat :(

**Comment by dvingerh** [comment] 2020-01-14 22:33
Snapchat is one of the worst APIs to work with, even their public (undocumented) api endpoints to view stories in browser keeps changing every time and I'm simply not able to work on it all the time.
